### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by kennyparsons** [tob123/piwigo#1]
I'm getting a lot of permission denied errors in my logs after running this container;
`cp: can't create directory '/piwigo/themes/dark': Permission denied
cp: can't create directory '/piwigo/themes/clear': Permission denied
cp: can't create directory '/piwigo/themes/elegant': Permission denied
cp: can't create directory '/piwigo/themes/Sylvia': Permission denied
cp: can't create directory '/piwigo/themes/default': Permission denied
cp: can't create '/piwigo/themes/index.php': Permission denied`

I'm running the container as root, and even tried running it privileged. Any ideas?

**Comment by tob123** [comment]
Hello,
thanks for trying the piwigo container. i did not write a lot of instructions yet how to use this container but let's see if we can make it work for you..

usage of volumes are recommended (also to keep your pictures and piwigo settings across container upgrades)

i use volumes in docker-compose for the container and set owner to the apache user on the host 
(works ok for me).
volume part from docker-compose as an example:

      volumes:
        - /bla_bla/piwigo/_data:/piwigo/_data
        - /bla_bla/piwigo/local:/piwigo/local
        - /bla_bla/piwigo/themes:/piwigo/themes
        - /bla_bla/piwigo/template-extension:/piwigo/template-extension
        - /bla_bla/piwigo/plugins:/piwigo/plugins
        - /bla_bla/piwigo/upload:/piwigo/upload
        - /bla_bla/piwigo/galleries:/piwigo/galleries
        - pw_built:/pw_built
    volumes:
    pw_built:

and on the host that has the docker-compose file make sure the dirs are there and have the right ownership.
for example for the directory that produces the error:

    mkdir -p /bla_bla/piwigo/themes
    chown 100:82 /bla_bla/piwigo/themes

repeat for the other dirs or use the below script:

    #!/bin/bash
    US_ID=100
    GR_ID=82
    BASEVOL=/bla_bla/piwigo
    if [ ! -d ${BASEVOL} ]; then
    mkdir -p $BASEVOL
    fi
    for i in _data themes plugins local template-extension upload galleries; do
    if [ ! -d ${BASEVOL}/${i} ]; then
    mkdir ${BASEVOL}/${i}
    fi
    chown ${US_ID}:${GR_ID} ${BASEVOL}/${i}
    done

let me know if this helps ?
